export default {
    SET_ROUTER_DATA: "SET_ROUTER_DATA",

    SET_PROFILE_CONTACTS_DATA: "SET_PROFILE_CONTACTS_DATA",
    SET_PROFILE_PWD_DATA: "SET_PROFILE_PWD_DATA",
    SET_PROFILE_ORGS_DATA: "SET_PROFILE_ORGS_DATA",

    SET_MYBROADCASTS_DATA: "SET_MYBROADCASTS_DATA",

    SET_ADMIN_ORG: "SET_ADMIN_ORG",

    SET_ADMIN_USERS_DATA: "SET_ADMIN_USERS_DATA",
    SET_ADMIN_GROUPS_DATA: "SET_ADMIN_GROUPS_DATA"
};
